<template>
  <component
    :is="iconComponent"
    :class="sizeClass"
    :size="sizePixels"
    :weight="weight"
    :aria-hidden="title ? undefined : true"
    :aria-label="title"
  />
</template>

<script setup lang="ts">
import { computed, type Component } from 'vue'
import {
  PhArrowDown,
  PhArrowLeft,
  PhArrowRight,
  PhArrowSquareOut,
  PhArrowUp,
  PhArrowsClockwise,
  PhArrowsDownUp,
  PhBell,
  PhBookOpen,
  PhBrain,
  PhCalculator,
  PhCalendarBlank,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhCaretUp,
  PhChartBar,
  PhChatCircle,
  PhChatCircleDots,
  PhCheck,
  PhCheckCircle,
  PhClipboardText,
  PhClock,
  PhCloud,
  PhCopy,
  PhCpu,
  PhCreditCard,
  PhCube,
  PhCurrencyDollar,
  PhDatabase,
  PhDotsThree,
  PhDownloadSimple,
  PhEnvelope,
  PhEye,
  PhEyeSlash,
  PhFileText,
  PhFire,
  PhFlask,
  PhFunnel,
  PhGearSix,
  PhGift,
  PhGlobe,
  PhHardDrives,
  PhHouse,
  PhInfo,
  PhKey,
  PhLightbulb,
  PhLightning,
  PhLink,
  PhList,
  PhLock,
  PhMagnifyingGlass,
  PhMoon,
  PhPencilSimple,
  PhPlay,
  PhPlus,
  PhProhibit,
  PhQuestion,
  PhSealCheck,
  PhShieldCheck,
  PhSignIn,
  PhSignOut,
  PhSortAscending,
  PhSparkle,
  PhSquaresFour,
  PhSun,
  PhSwap,
  PhTerminalWindow,
  PhTrash,
  PhTray,
  PhTrendUp,
  PhTrophy,
  PhUploadSimple,
  PhUser,
  PhUserCircle,
  PhUserPlus,
  PhUsers,
  PhWarning,
  PhWarningCircle,
  PhX,
  PhXCircle,
} from '@phosphor-icons/vue'

const icons = {
  play: PhPlay,
  refresh: PhArrowsClockwise,
  edit: PhPencilSimple,
  trash: PhTrash,
  plus: PhPlus,
  search: PhMagnifyingGlass,
  more: PhDotsThree,
  chart: PhChartBar,
  clock: PhClock,
  link: PhLink,
  sync: PhArrowsClockwise,
  chevronDown: PhCaretDown,
  chevronRight: PhCaretRight,
  chevronLeft: PhCaretLeft,
  check: PhCheck,
  x: PhX,
  eye: PhEye,
  eyeOff: PhEyeSlash,
  cog: PhGearSix,
  grid: PhSquaresFour,
  chat: PhChatCircleDots,
  lightbulb: PhLightbulb,
  arrowRight: PhArrowRight,
  arrowLeft: PhArrowLeft,
  arrowUp: PhArrowUp,
  arrowDown: PhArrowDown,
  arrowsUpDown: PhArrowsDownUp,
  chevronUp: PhCaretUp,
  externalLink: PhArrowSquareOut,
  checkCircle: PhCheckCircle,
  xCircle: PhXCircle,
  exclamationCircle: PhWarningCircle,
  exclamationTriangle: PhWarning,
  trophy: PhTrophy,
  infoCircle: PhInfo,
  questionCircle: PhQuestion,
  user: PhUser,
  userCircle: PhUserCircle,
  userPlus: PhUserPlus,
  users: PhUsers,
  document: PhFileText,
  clipboard: PhClipboardText,
  copy: PhCopy,
  inbox: PhTray,
  download: PhDownloadSimple,
  upload: PhUploadSimple,
  filter: PhFunnel,
  globe: PhGlobe,
  sort: PhSortAscending,
  key: PhKey,
  lock: PhLock,
  shield: PhShieldCheck,
  menu: PhList,
  calendar: PhCalendarBlank,
  home: PhHouse,
  terminal: PhTerminalWindow,
  gift: PhGift,
  creditCard: PhCreditCard,
  mail: PhEnvelope,
  chartBar: PhChartBar,
  trendingUp: PhTrendUp,
  database: PhDatabase,
  cube: PhCube,
  bell: PhBell,
  bolt: PhLightning,
  sparkles: PhSparkle,
  cloud: PhCloud,
  server: PhHardDrives,
  sun: PhSun,
  moon: PhMoon,
  book: PhBookOpen,
  dollar: PhCurrencyDollar,
  ban: PhProhibit,
  login: PhSignIn,
  logout: PhSignOut,
  swap: PhSwap,
  beaker: PhFlask,
  cpu: PhCpu,
  chatBubble: PhChatCircle,
  calculator: PhCalculator,
  fire: PhFire,
  badge: PhSealCheck,
  brain: PhBrain,
} satisfies Record<string, Component>

type IconName = keyof typeof icons
type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'

const props = withDefaults(defineProps<{
  name: IconName
  size?: IconSize
  strokeWidth?: number
  title?: string
}>(), {
  size: 'md',
  strokeWidth: 1.5,
})

const iconComponent = computed(() => icons[props.name])
const weight = computed(() => (props.strokeWidth >= 2 ? 'bold' : 'regular'))
const sizePixels = computed(() => ({ xs: 12, sm: 16, md: 20, lg: 24, xl: 32 })[props.size])
const sizeClass = computed(() => ({
  xs: 'h-3 w-3',
  sm: 'h-4 w-4',
  md: 'h-5 w-5',
  lg: 'h-6 w-6',
  xl: 'h-8 w-8',
})[props.size])
</script>
